version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/packages/buster-cli"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
