packages:
  - packages/*
  - apps/web
  - apps/server
  - apps/electric-server
  - apps/trigger
  - apps/web-tss
  - apps/api

catalog:
  '@aws-sdk/client-s3': ^3.873.0
  '@supabase/supabase-js': ^2.57.0
  '@trigger.dev/build': ^4.0.2
  '@trigger.dev/sdk': ^4.0.2
  '@electric-sql/client': ^1.0.9
  ai: ^5.0.30
  axios: ^1.11.0
  braintrust: ^0.2.4
  dotenv: ^17.2.2
  drizzle-orm: ^0.44.5
  lodash-es: ^4.17.21
  hono: ^4.9.6
  octokit: ^5.0.3
  pg: ^8.16.3
  tsup: ^8.5.0
  tsx: ^4.20.5
  uuid: ^11.1.0
  vite: ^7.1.4
  vite-tsconfig-paths: 6.0.0-beta.4
  vitest: ^3.2.4
  zod: ^3.25.0
