packages:
  - packages/*
  - apps/web
  - apps/server
  - apps/electric-server
  - apps/trigger
  - apps/web-tss
  - apps/api

catalog:
  '@aws-sdk/client-s3': ^3.873.0
  '@supabase/supabase-js': ^2.50.0
  '@trigger.dev/build': ^4.0.0
  '@trigger.dev/sdk': ^4.0.0
  ai: ^5.0.5
  axios: ^1.11.0
  braintrust: ^0.2.4
  dotenv: ^17.2.1
  drizzle-orm: ^0.44.4
  hono: ^4.9.2
  pg: ^8.16.3
  remark-gfm: ^4.0.1
  remark-math: ^6.0.0
  tsup: ^8.5.0
  tsx: ^4.20.4
  uuid: ^11.1.0
  vite: ^7.1.3
  vite-tsconfig-paths: 6.0.0-beta.4
  vitest: ^3.2.4
  zod: ^3.25.0
