packages:
  # Core packages
  - "packages/*"

  # Applications
  - "apps/web"
  - "apps/server"
  - "apps/electric-server"
  - "apps/trigger"
  - "apps/api"

catalog:
  "@supabase/supabase-js": "^2.50.0"
  "@trigger.dev/build": "^4.0.0-v4-beta.27"
  "@trigger.dev/sdk": "^4.0.0-v4-beta.27"
  "@platejs/autoformat": "^49.0.0"
  "@platejs/basic-nodes": "^49.0.0"
  ai: "^5.0.5"
  "@platejs/basic-styles": "^49.0.0"
  "@platejs/date": "^49.0.2"
  "@platejs/indent": "^49.0.0"
  "@platejs/layout": "^49.2.1"
  "@platejs/link": "^49.1.1"
  "@platejs/list": "^49.2.0"
  "@platejs/markdown": "^49.2.1"
  "@platejs/math": "^49.0.0"
  "@platejs/media": "^49.0.0"
  "@platejs/table": "^49.1.13"
  "@platejs/toc": "^49.0.0"
  "@platejs/toggle": "^49.0.0"
  axios: "^1.10.0"
  "braintrust": "^0.0.209"
  dotenv: "^17.2.0"
  drizzle-orm: "^0.44.2"
  hono: "^4.8.0"
  pg: "^8.16.2"
  platejs: "^49.2.9"
  "remark-gfm": "^4.0.1"
  "remark-math": "^6.0.0"
  tsup: "^8.5.0"
  tsx: "^4.20.0"
  uuid: "^11.0.0"
  vite: "^7.0.0"
  "vite-tsconfig-paths": "6.0.0-beta.3"
  vitest: "^3.2.4"
  zod: "^3.25.0"
