# wrangler.toml
"$schema" = "node_modules/wrangler/config-schema.json"
name = "web-tss"
main = "./.output/server/index.mjs"
compatibility_date = "2025-09-02"
compatibility_flags = ["nodejs_compat", "no_nodejs_compat_v2"]

[assets]
directory = ".output/public"

[observability]
enabled = true