name: buster
include:
  - "**/*.test.yaml"
  - "**/*.module.yaml"
environments:
  - name: development
    baseUrl: http://localhost:3000
    envVariables:
      EMAIL: "chad@buster.so"
      PASSWORD: "password"
