name: Build, Lint, and Unit Tests

on:
  pull_request:

# Cancel in-progress runs when a new commit is pushed to the same PR
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  # Build job - runs in parallel
  build:
    name: Build
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 10
    environment: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: ./.github/actions/setup-node-env
        with:
          cache-key: build-lint-unit

      - name: Build all packages
        run: pnpm turbo build
        env:
          NODE_ENV: production
          SKIP_ENV_CHECK: true
          TURBO_CACHE_DIR: .turbo
          TURBO_TELEMETRY_DISABLED: 1
          # Pass all secrets from the testing environment for build
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          VITE_PUBLIC_API_URL: ${{ secrets.VITE_PUBLIC_API_URL }}
          VITE_PUBLIC_API2_URL: ${{ secrets.VITE_PUBLIC_API2_URL }}
          VITE_PUBLIC_SUPABASE_URL: ${{ secrets.VITE_PUBLIC_SUPABASE_URL }}
          VITE_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.VITE_PUBLIC_SUPABASE_ANON_KEY }}
          VITE_PUBLIC_URL: ${{ secrets.VITE_PUBLIC_URL }}

  # Lint job - runs in parallel
  lint:
    name: Lint
    runs-on: blacksmith-2vcpu-ubuntu-2404
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: ./.github/actions/setup-node-env
        with:
          cache-key: build-lint-unit

      - name: Lint all packages
        run: pnpm turbo lint
        env:
          TURBO_CACHE_DIR: .turbo
          TURBO_TELEMETRY_DISABLED: 1

  # Test job - runs after build completes
  test:
    name: Test
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: ./.github/actions/setup-node-env
        with:
          cache-key: build-lint-unit

      - name: Build required packages
        run: pnpm turbo build --filter="!@buster-app/web"
        env:
          NODE_ENV: production
          SKIP_ENV_CHECK: true
          TURBO_CACHE_DIR: .turbo
          TURBO_TELEMETRY_DISABLED: 1

      - name: Run all unit tests
        run: pnpm turbo test:unit
        env:
          TURBO_CACHE_DIR: .turbo
          TURBO_TELEMETRY_DISABLED: 1

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: |
            **/coverage/**
            !**/coverage/tmp/**
          retention-days: 7

  # Services health check - runs after build completes
  services-health:
    name: Services Health Check
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 10
    needs: build  # Wait for build to complete
    environment: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: ./.github/actions/setup-node-env
        with:
          cache-key: build-lint-unit

      - name: Cache Supabase CLI
        id: cache-supabase
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/supabase
          key: ${{ runner.os }}-supabase-cli-latest
          restore-keys: |
            ${{ runner.os }}-supabase-cli-

      - name: Install Supabase CLI
        if: steps.cache-supabase.outputs.cache-hit != 'true'
        run: |
          wget -qO- https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz | tar xvz
          sudo mv supabase /usr/local/bin/
          sudo chmod +x /usr/local/bin/supabase

      - name: Start services
        run: |
          pnpm turbo start &
          echo $! > turbo.pid
          echo "Started turbo with PID $(cat turbo.pid)"
        env:
          SKIP_ENV_CHECK: true
          TURBO_CACHE_DIR: .turbo
          TURBO_TELEMETRY_DISABLED: 1
          # Pass all secrets from the testing environment
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_PUBLIC_URL: ${{ secrets.SUPABASE_PUBLIC_URL }}
          VITE_PUBLIC_API_URL: ${{ secrets.VITE_PUBLIC_API_URL }}
          VITE_PUBLIC_API2_URL: ${{ secrets.VITE_PUBLIC_API2_URL }}
          VITE_PUBLIC_WEB_SOCKET_URL: ${{ secrets.VITE_PUBLIC_WEB_SOCKET_URL }}
          VITE_PUBLIC_URL: ${{ secrets.VITE_PUBLIC_URL }}
          VITE_PUBLIC_SUPABASE_URL: ${{ secrets.VITE_PUBLIC_SUPABASE_URL }}
          VITE_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.VITE_PUBLIC_SUPABASE_ANON_KEY }}
          VITE_PUBLIC_WS_URL: ${{ secrets.VITE_PUBLIC_WS_URL }}
          VITE_PUBLIC_POSTHOG_KEY: ${{ secrets.VITE_PUBLIC_POSTHOG_KEY }}
          VITE_PUBLIC_POSTHOG_HOST: ${{ secrets.VITE_PUBLIC_POSTHOG_HOST }}
          VITE_SLACK_APP_SUPPORT_URL: ${{ secrets.VITE_SLACK_APP_SUPPORT_URL }}
          VITE_PRIVATE_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.VITE_PRIVATE_SUPABASE_SERVICE_ROLE_KEY }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          ELECTRIC_PROXY_URL: ${{ secrets.ELECTRIC_PROXY_URL }}
          ELECTRIC_PORT: ${{ secrets.ELECTRIC_PORT }}
          ELECTRIC_INSECURE: ${{ secrets.ELECTRIC_INSECURE }}
          ELECTRIC_SECRET: ${{ secrets.ELECTRIC_SECRET }}
          ELECTRIC_SOURCE_ID: ${{ secrets.ELECTRIC_SOURCE_ID }}
          RERANK_API_KEY: ${{ secrets.RERANK_API_KEY }}
          RERANK_MODEL: ${{ secrets.RERANK_MODEL }}
          RERANK_BASE_URL: ${{ secrets.RERANK_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          TURBOPUFFER_API_KEY: ${{ secrets.TURBOPUFFER_API_KEY }}
          TURBOPUFFER_REGION: ${{ secrets.TURBOPUFFER_REGION }}
          POSTHOG_TELEMETRY_KEY: ${{ secrets.POSTHOG_TELEMETRY_KEY }}
          BRAINTRUST_KEY: ${{ secrets.BRAINTRUST_KEY }}
          BRAINTRUST_API_KEY: ${{ secrets.BRAINTRUST_API_KEY }}
          TRIGGER_SECRET_KEY: ${{ secrets.TRIGGER_SECRET_KEY }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
          GITHUB_APP_ID: ${{ secrets.GITHUB_APP_ID }}
          GITHUB_APP_PRIVATE_KEY_BASE64: ${{ secrets.GITHUB_APP_PRIVATE_KEY_BASE64 }}
          GITHUB_WEBHOOK_SECRET: ${{ secrets.GITHUB_WEBHOOK_SECRET }}
          # Additional variables from .env
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          BUSTER_URL: ${{ secrets.BUSTER_URL }}
          BUSTER_WH_TOKEN: ${{ secrets.BUSTER_WH_TOKEN }}
          POOLER_URL: ${{ secrets.POOLER_URL }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
          SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_APP_SUPPORT_URL: ${{ secrets.SLACK_APP_SUPPORT_URL }}
          AI_GATEWAY_API_KEY: ${{ secrets.AI_GATEWAY_API_KEY }}
          DAYTONA_API_KEY: ${{ secrets.DAYTONA_API_KEY }}
          TEST_GITHUB_PAT: ${{ secrets.TEST_GITHUB_PAT }}
          TEST_SAMPLE_REPO: ${{ secrets.TEST_SAMPLE_REPO }}

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to start..."
          sleep 30
          
          # Check each service with retries
          for port in 3000 3001 3002; do
            echo "Checking localhost:$port..."
            max_attempts=30
            attempt=0
            while [ $attempt -lt $max_attempts ]; do
              if curl -f -s -o /dev/null -w "%{http_code}" http://localhost:$port | grep -q "200\|301\|302\|404"; then
                echo "✅ Service on port $port is responding"
                break
              else
                echo "Waiting for service on port $port (attempt $((attempt+1))/$max_attempts)..."
                sleep 2
                attempt=$((attempt+1))
              fi
            done
            if [ $attempt -eq $max_attempts ]; then
              echo "❌ Service on port $port failed to respond"
              exit 1
            fi
          done
          
          echo "All services are healthy!"

      - name: Stop services
        if: always()
        run: |
          if [ -f turbo.pid ]; then
            kill $(cat turbo.pid) || true
            rm turbo.pid
          fi