name: Database Migrations

on:
  push:
    branches: [main, staging]
    paths:
      - 'packages/database/drizzle/**'
      - 'packages/database/drizzle.config.ts'
      - '.github/workflows/database-migrations.yml'
      - 'packages/database/package.json'
  pull_request:
    types: [closed]
    branches: [main, staging]
    paths:
      - 'packages/database/drizzle/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run migrations against'
        required: true
        type: choice
        options:
          - main
          - staging
        default: staging

# Only one migration per environment at a time
concurrency:
  group: db-migrate-${{ github.ref }}
  cancel-in-progress: false  # Never cancel migrations

jobs:
  detect-changes:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    if: github.event_name != 'workflow_dispatch'
    outputs:
      migrations-changed: ${{ steps.check.outputs.migrations }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check for migration changes
        id: check
        run: |
          echo "Checking for migration changes..."
          
          # For PR merges, compare with base branch
          if [ "${{ github.event_name }}" = "pull_request" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            BASE_REF="${{ github.base_ref }}"
            echo "PR merged - comparing with $BASE_REF"
            CHANGED_FILES=$(git diff --name-only origin/$BASE_REF...HEAD)
          # For direct pushes, compare with previous commit
          else
            echo "Direct push - comparing with previous commit"
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD 2>/dev/null || git diff --name-only HEAD~1 HEAD)
          fi
          
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          if echo "$CHANGED_FILES" | grep -q "packages/database/drizzle/.*\.sql$"; then
            echo "migrations=true" >> $GITHUB_OUTPUT
            echo "✅ Migration files changed - will run migrations"
          else
            echo "migrations=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No migration files changed"
          fi

  migrate:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    needs: [detect-changes]
    if: |
      always() && (
        github.event_name == 'workflow_dispatch' || 
        needs.detect-changes.outputs.migrations-changed == 'true'
      )
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.1
          
      - name: Setup Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'
      
      - name: Fix pnpm store permissions
        run: |
          STORE_PATH=$(pnpm store path --silent)
          if [ -d "$STORE_PATH" ]; then
            sudo chown -R $(whoami):$(whoami) "$STORE_PATH" || true
            chmod -R u+rw "$STORE_PATH" || true
          fi
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      
      - name: Run migrations
        run: pnpm run db:migrate
        env:
          DATABASE_URL: ${{ secrets.DB_URL }}
          NODE_TLS_REJECT_UNAUTHORIZED: '0'