name: Deploy Web to Production

on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
  workflow_dispatch:

# Cancel in-progress deployments when a new commit is pushed
concurrency:
  group: deploy-web-production-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-web-reusable.yml
    with:
      environment: production
      branch: main
      api_url: "https://api.buster.so"
      public_url: "https://platform.buster.so"
      supabase_url: "https://aofftppzkoydkyfrhrcj.supabase.co"
      supabase_anon_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZmZ0cHB6a295ZGt5ZnJocmNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjYzNTUzNDUsImV4cCI6MjA0MTkzMTM0NX0.sg_4VkZDpVDO51bMBsAOhNdU_AAXnH8bGqeK3UHHe-Q"
      posthog_key: "phc_CtxCFcicGmtdan7MnQTRc3AypAifI7FYsoVFv3WnCQc"
      api2_url: "https://api2.buster.so"
      enable_tanstack_panel: "false"
      wrangler_env: production
      worker_name: web-production
    secrets: inherit
