name: Deploy Web to Staging

on:
  push:
    branches:
      - staging
    paths:
      - "apps/web/**"
  workflow_dispatch:

# Cancel in-progress deployments when a new commit is pushed
concurrency:
  group: deploy-web-staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-web-reusable.yml
    with:
      environment: staging
      branch: staging
      api_url: https://api2staging.buster.so
      public_url: https://staging.buster.so
      supabase_url: https://vlelrtlxoixvaynaudau.supabase.co
      supabase_anon_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZWxydGx4b2l4dmF5bmF1ZGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjM3MzEyNzgsImV4cCI6MjAzOTMwNzI3OH0.nK2gZggez6r_F00Ci_fcMXPle5HWo9boGQ5mG3CERFs
      posthog_key: phc_CtxCFcicGmtdan7MnQTRc3AypAifI7FYsoVFv3WnCQc
      api2_url: https://stagingapi.buster.so
      enable_tanstack_panel: true
      wrangler_env: staging
      worker_name: web-staging
    secrets: inherit
