name: Deploy Trigger.dev Tasks

on:
  push:
    branches: [main, staging]

# Only one deployment per environment at a time
concurrency:
  group: trigger-deploy-${{ github.ref }}
  cancel-in-progress: false  # Never cancel deployments

jobs:
  deploy:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 22
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.0
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      
      - name: Mount pnpm store sticky disk
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-pnpm-store
          path: ${{ env.STORE_PATH }}
      
      - name: Mount Turbo cache sticky disk
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-turbo-cache
          path: ./.turbo
          
      - name: Install dependencies
        run: |
          # Remove any existing node_modules to avoid conflicts
          rm -rf node_modules
          pnpm install --frozen-lockfile --prefer-offline
        
      - name: 🚀 Deploy to ${{ github.ref_name == 'main' && 'Production' || 'Staging' }}
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
        run: |
          cd apps/trigger
          pnpm dlx trigger.dev@latest deploy --env ${{ github.ref_name == 'main' && 'production' || 'staging' }} 